I use this notebook to build the intuition behind how broadcasting is used to calculate nearest neighbours. This is useless by itself; you have been warned!!
___

In [4]:
import numpy as np

def stats(n):
    print(n.size, n.ndim, n.shape)

Suppose we have an array of four elements:

$a = [1, 2, 3, 4]$

How might we use broadcasting to calculate the difference of each pair of elements?

Step 1: transpose $a$ to get $a^t$

Step 2: calculate $a - a^t$

In [12]:

a = np.array([1, 2, 3, 4]).reshape(4, 1)

print("======== a =========")
stats(a)
print(a)
print("======== b =========")
b = a.reshape(1, 4)
stats(b)
print(b)
print("======== c = a - b =========")
c = a - b
stats(c)
print(c)
print("======== d = b - a =========")
d = b - a
stats(d)
print(d)

e = a.reshape(4, 1, 1)
print("======== e =========")
stats(e)
print(e)

f = a - e
print("======== f = a - e =========")
stats(f)
print(f)

g = e - a
print("======== g = e - a =========")
stats(g)
print(g)

======== a =========
4 2 (4, 1)
[[1]
 [2]
 [3]
 [4]]
======== b =========
4 2 (1, 4)
[[1 2 3 4]]
======== c = a - b =========
16 2 (4, 4)
[[ 0 -1 -2 -3]
 [ 1  0 -1 -2]
 [ 2  1  0 -1]
 [ 3  2  1  0]]
======== d = b - a =========
16 2 (4, 4)
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]]
======== e =========
4 3 (4, 1, 1)
[[[1]]

 [[2]]

 [[3]]

 [[4]]]
======== f = a - e =========
16 3 (4, 4, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[-1]
  [ 0]
  [ 1]
  [ 2]]

 [[-2]
  [-1]
  [ 0]
  [ 1]]

 [[-3]
  [-2]
  [-1]
  [ 0]]]
======== g = e - e =========
16 3 (4, 4, 1)
[[[ 0]
  [-1]
  [-2]
  [-3]]

 [[ 1]
  [ 0]
  [-1]
  [-2]]

 [[ 2]
  [ 1]
  [ 0]
  [-1]]

 [[ 3]
  [ 2]
  [ 1]
  [ 0]]]


General observation: we keep the last index 'constant', swap the next-to-last two indices and then do the broadcast subtraction

So if we have the last index representing $k$ co-ordinates, we keep this constant, and swap the next two!

So let's say we have a 2-d matrix, where each row is the co-ordinate of a point

$b = [ [1, 2], [4, 5], [7, 8], [10, 11] ]$

In [15]:
a = np.array([ [1, 2], [4, 5], [7, 8], [10, 11] ])
stats(a)
print(a)

8 2 (4, 2)
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


This is implicitly a 3 dimensional array, with lengths 1, 4, 2 along each dimension. We can swap the first two

In [16]:
b = a.reshape(4, 1, 2)
stats(b)
print(b)

8 3 (4, 1, 2)
[[[ 1  2]]

 [[ 4  5]]

 [[ 7  8]]

 [[10 11]]]


... and then do the subtraction:

In [17]:
c = a - b
stats(c)
print(c)

32 3 (4, 4, 2)
[[[ 0  0]
  [ 3  3]
  [ 6  6]
  [ 9  9]]

 [[-3 -3]
  [ 0  0]
  [ 3  3]
  [ 6  6]]

 [[-6 -6]
  [-3 -3]
  [ 0  0]
  [ 3  3]]

 [[-9 -9]
  [-6 -6]
  [-3 -3]
  [ 0  0]]]
