The fundamental data structure provided by the numpy library is the ndarray

This notebook covers some of the basics of ndarrays: how to create one, access the elements and how to index into it. 

The 'Big 4' advantages of ndarrays are:
1. Universal functions
2. Aggregations
3. Broadcasting
4. Fancy indexing (incl. slicing and masking)


In [2]:
import numpy as np

In [22]:
a = np.array([1., 2, 3, 4, 6])
print(type(a))

<class 'numpy.ndarray'>


In [23]:
print(a.shape, a.size, a.ndim, a.dtype)

(5,) 5 1 float64


In [16]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
def properties(a):
    #return 'ndim: ', a.ndim, 'shape: ', a.shape, 'size: ', a.size, 'type: ', a.dtype
    return f'ndim: {a.ndim} shape: {a.shape} size: {a.size } type: {a.dtype}'

In [32]:
c = b.reshape(2, 5)
print(properties(c))
print(b.shape, b.size, b.ndim)
print(b)
print(c.shape, c.size, c.ndim)
print(c)

ndim: 2 shape: (2, 5) size: 10 type: int32
(10,) 10 1
[0 1 2 3 4 5 6 7 8 9]
(2, 5) 10 2
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
c[:,4]

array([4, 9])

In [30]:
c[-1,3]

8

In [3]:
d = np.arange(1729).reshape(7, 247)
print(d)

[[   0    1    2 ...  244  245  246]
 [ 247  248  249 ...  491  492  493]
 [ 494  495  496 ...  738  739  740]
 ...
 [ 988  989  990 ... 1232 1233 1234]
 [1235 1236 1237 ... 1479 1480 1481]
 [1482 1483 1484 ... 1726 1727 1728]]


In [4]:
d = d.reshape(7, 13, 19)
print(d)

[[[   0    1    2 ...   16   17   18]
  [  19   20   21 ...   35   36   37]
  [  38   39   40 ...   54   55   56]
  ...
  [ 190  191  192 ...  206  207  208]
  [ 209  210  211 ...  225  226  227]
  [ 228  229  230 ...  244  245  246]]

 [[ 247  248  249 ...  263  264  265]
  [ 266  267  268 ...  282  283  284]
  [ 285  286  287 ...  301  302  303]
  ...
  [ 437  438  439 ...  453  454  455]
  [ 456  457  458 ...  472  473  474]
  [ 475  476  477 ...  491  492  493]]

 [[ 494  495  496 ...  510  511  512]
  [ 513  514  515 ...  529  530  531]
  [ 532  533  534 ...  548  549  550]
  ...
  [ 684  685  686 ...  700  701  702]
  [ 703  704  705 ...  719  720  721]
  [ 722  723  724 ...  738  739  740]]

 ...

 [[ 988  989  990 ... 1004 1005 1006]
  [1007 1008 1009 ... 1023 1024 1025]
  [1026 1027 1028 ... 1042 1043 1044]
  ...
  [1178 1179 1180 ... 1194 1195 1196]
  [1197 1198 1199 ... 1213 1214 1215]
  [1216 1217 1218 ... 1232 1233 1234]]

 [[1235 1236 1237 ... 1251 1252 1253]
  [1254 1255

In [37]:
d2 = d[:,9:11,15:17]
print(d2.shape)
print(d2)

(7, 2, 2)
[[[ 186  187]
  [ 205  206]]

 [[ 433  434]
  [ 452  453]]

 [[ 680  681]
  [ 699  700]]

 [[ 927  928]
  [ 946  947]]

 [[1174 1175]
  [1193 1194]]

 [[1421 1422]
  [1440 1441]]

 [[1668 1669]
  [1687 1688]]]


In [44]:
print(d2[5,0,1])
foo = np.where(d == 1422)
print(foo)
print(d[foo])

1422
(array([5], dtype=int64), array([9], dtype=int64), array([16], dtype=int64))
[1422]


In [45]:
d2[5, 0, 1] = 42
print(d[foo])

[42]


In [5]:
print(d.shape)

(7, 13, 19)


In [8]:
e = d[0]

In [10]:
f = e[0]

In [11]:
f[0]

0

In [12]:
e[0][0]

0

In [13]:
d[0][0][0]

0

Exercise:

- Select the 2nd block, row 2-4, column 5-8
- Select the last two blocks, first row, 2nd column
- Select the first two rows and last two columns of the first block. What are the dimensions of this matrix?

<img src="3d ndarray.png">
<img src="3d ndarray-col1.png">
<img src="3d ndarray-col2.png">
<img src="3d ndarray-col3.png">


<img src="3d ndarray-row1.png">
<img src="3d ndarray-row1-1.png">
<img src="3d ndarray-row2.png">
<img src="3d ndarray-block1.png">
<img src="3d ndarray-block2.png">

In [33]:
e = np.empty((12, 1))
print(e)
e = np.ones((3, 3))
print(e)

[[9.39267362e-312]
 [9.39267362e-312]
 [9.39267362e-312]
 [1.26974871e-321]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
## creating a mask
dmod10 = d % 10
lt4 = dmod10 < 4
print(lt4)

[[[ True  True  True ... False False False]
  [False  True  True ... False False False]
  [False False  True ... False False False]
  ...
  [ True  True  True ... False False False]
  [False  True  True ... False False False]
  [False False  True ... False False False]]

 [[False False False ...  True False False]
  [False False False ...  True  True False]
  [False False False ...  True  True  True]
  ...
  [False False False ...  True False False]
  [False False False ...  True  True False]
  [False False False ...  True  True  True]]

 [[False False False ...  True  True  True]
  [ True False False ... False  True  True]
  [ True  True False ... False False  True]
  ...
  [False False False ...  True  True  True]
  [ True False False ... False  True  True]
  [ True  True False ... False False  True]]

 ...

 [[False False  True ... False False False]
  [False False False ...  True False False]
  [False False False ...  True  True False]
  ...
  [False False  True ... False False Fal

In [14]:
# applying a mask to an array returns 
# an array containing the values corresponding 
# to where the mask has a true
dlt4 = d[lt4]
print(dlt4.size, dlt4.shape, dlt4.ndim)

692 (692,) 1


In [17]:
dlt5 = d < 5
print(dlt5)

[[[ True  True  True ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]
  ...
  [False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]
  ...
  [False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]]

 [[False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]
  ...
  [False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]]

 ...

 [[False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]
  ...
  [False False False ... False False Fal