A gentle introduction to broadcasting. Get familiar with this before jumping into calculating nearest neighbours

In [1]:
import numpy as np

In [3]:
#a = np.zeros(9).reshape(3, 3)
a = np.zeros((3, 3))

In [4]:
b = np.arange(3)

In [5]:
c = a + b
print(a, b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [0 1 2]
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [5]:
b = b.reshape(3, 1)
c = a + b
print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0]
 [1]
 [2]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


Brahmagupta-Fibonacci Identity (https://en.wikipedia.org/wiki/Brahmagupta%E2%80%93Fibonacci_identity): The product of two sums of two squares can be expressed as the sum of two squares in two different ways

In [6]:
# n1 = int(input("Enter a square number: "))

In [17]:
n1 = 1
n2 = 2
n3 = 3
n4 = 4

In [18]:
s1 = np.array([n1, n2])
s2 = np.array([n3, n4]).reshape(2, 1)
print(s1)
print(s2)

[1 2]
[[3]
 [4]]


In [19]:
s1_sq = s1 ** 2
s2_sq = s2 ** 2
print(s1_sq)
print(s2_sq)
new_nums = s1_sq * s2_sq
print(new_nums)
nn_sq = np.sum(new_nums)
print(nn_sq)

[1 4]
[[ 9]
 [16]]
[[ 9 36]
 [16 64]]
125


In [20]:
nn = s1 * s2
print(nn)

[[3 6]
 [4 8]]


This can be extended to Euler's four-square identity and Degen's eight-square identity